" Vundle
" -------
set nocompatible                                      " be iMproved, required
filetype off                                          " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'ctrlpvim/ctrlp.vim'                           " CtrlP Fuzzy File Finder
Plugin 'vim-ruby/vim-ruby'                            " Vim Ruby
Plugin 'tpope/vim-rails'                              " Rails specific stuff
Plugin 'tpope/vim-haml'                               " Haml syntax highlighting
Plugin 'slim-template/vim-slim'                       " Slim syntax highlighting
Plugin 'kchmck/vim-coffee-script'                     " CoffeeScript
Plugin 'scrooloose/nerdtree'                          " Nerd Tree view
Plugin 'danro/rename.vim'                             " Rename the current file in the vim buffer
Plugin 'christoomey/vim-tmux-navigator'               " Navigation between tmux panes and vim splits

" All of your Plugins must be added before the following line
call vundle#end()                                     " required
filetype plugin indent on                             " required

set nocompatible                                      " We're running Vim, not Vi!
syntax on                                             " Enable syntax highlighting
filetype on                                           " Enable filetype detection
filetype indent on                                    " Enable filetype-specific indenting
filetype plugin on                                    " Enable filetype-specific plugins


" Plugin configuration
" --------------------
" Make CtrlP use ag for listing the files. Way faster and no useless files.
let g:ctrlp_user_command = 'ag %s -l --hidden --nocolor -g ""'
let g:ctrlp_use_caching = 0


" Key mappings
" -------------
" Easy access to start of line in Normal mode
nmap 0 ^

" Easy escape from Insert mode
imap jk <esc>
imap kj <esc>

" Easier navigation between splits
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" General configurations
" -----------------------
set number                                              " Enable numbered lines
set expandtab                                           " Convert <tab> to spaces
set tabstop=2                                           " Set tab space to 2
set splitbelow                                          " More natural split
set splitright                                          " More natural split


